// <auto-generated />
using System;
using CoronaPredictionsAspNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoronaPredictionsAspNetCore.Migrations
{
    [DbContext(typeof(PredictCoronaCasesDBContext))]
    partial class PredictCoronaCasesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoronaPredictionsAspNetCore.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WorkDescription")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CoronaPredictionsAspNetCore.Models.Predictions", b =>
                {
                    b.Property<int>("PredictionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CasesOfPrediction")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfPrediction")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfPrediction")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PredictionID");

                    b.ToTable("Prediction");
                });

            modelBuilder.Entity("CoronaPredictionsAspNetCore.Models.RealCases", b =>
                {
                    b.Property<int>("RealCaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRealCases")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfRealCases")
                        .HasColumnType("int");

                    b.Property<int>("RealCasesNo")
                        .HasColumnType("int");

                    b.HasKey("RealCaseID");

                    b.ToTable("RealCasesEachDay");
                });
#pragma warning restore 612, 618
        }
    }
}
